image: Visual Studio 2017

version: build-{build}

environment:
  apksign_keystore_pass:
    secure: eqbI6nZfLLOhPTrlSfS81gUsWdjueY6kyXIRJRSFFUw=
  apksign_keystore_secret:
    secure: WgV6cKnoTywiyKb3ZwoApp32DCB79NfIrRPgkAmjtMc=

clone_script:
  - cmd: >-
      git config --global core.autocrlf false
      && git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      && cd %APPVEYOR_BUILD_FOLDER%
      && git checkout -qf %APPVEYOR_REPO_COMMIT%
      && git submodule update --init --recursive


before_build:
  - bash build.sh pre-build

configuration: Release

build:
  parallel: true
  project: Naive.sln

after_build:
  - bash build.sh deploy
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - buildapk.bat

test: off

artifacts:
  - path: bin/upload/*

deploy:
  description: 'Appveyor build'
  provider: GitHub
  auth_token:
    secure: 0f7Tju3g2JTTgZ6/yfzXwD4AmGnmwBqdeuffFJj1X3faN0o1NmgAoOxnK6gnEOux
  artifact: /.*/
  draft: false
  prerelease: false
  on:
    # branch: master
    appveyor_repo_tag: true


# cache:
#   - '%USERPROFILE%\.nuget\packages'
